on:
  workflow_call:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.2.0
    - name: Install helm
      uses: azure/setup-helm@v1.1
    - name: Upgrade helm deps
      env:
        HELM_EXPERIMENTAL_OCI: 1
      working-directory: ./helm
      run: helm dep up
    - name: Lint helm
      working-directory: ./helm
      run: |
        helm lint
        helm template .
