on:
  workflow_call:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.2.0
    - name: Lint npm
      run: |
        npm ci
        npm run prettier --if-present
        npm run eslint --if-present
        npm run stylelint --if-present
        npm run type-check --if-present